# docker-compose.yml: Defines services for local development.
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - BACKEND_LLM=local
      - PORT=8080

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_DEV_API_URL=http://backend:8080
      - CHOKIDAR_USEPOLLING=true
